spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file://tmp/ms-config-properties/{application}/{profile},
            file://tmp/ms-config-properties/global/{profile}
